load(":catalog.bzl", "declare_test_guest_targets")
load(
    ":test_guest.bzl",
    "test_guest_base_image",
    "test_guest_host_tools",
    "test_guest_test",
    "test_guest_variant",
)

exports_files([
    "build-image.sh",
    "catalog.bzl",
    "configuration/docker.yml",
    "configuration/podman.yml",
    "configuration/selinux.yml",
    "extensions.bzl",
    "host-tools.BUILD.bazel",
    "host-tools.nix",
    "image-seal.sh",
    "nixpkgs.nix",
    "run.sh",
    "test-guest.MODULE.bazel",
])

toolchain_type(name = "host_tools_toolchain_type")

test_guest_host_tools(
    name = "nix_host_tools",
    all_files = "@test_guest_host_tools//:all",
    ansible_version = "@test_guest_host_tools//:ansible_version",
    bash = "@test_guest_host_tools//:bash",
    jq = "@test_guest_host_tools//:jq",
    qemu_img = "@test_guest_host_tools//:qemu_img",
    qemu_version = "@test_guest_host_tools//:qemu_version",
    runner = "@test_guest_host_tools//:runner",
    sha256sum = "@test_guest_host_tools//:sha256sum",
)

toolchain(
    name = "nix_host_tools_toolchain",
    toolchain = ":nix_host_tools",
    toolchain_type = ":host_tools_toolchain_type",
    use_target_platform_constraints = True,
)

config_setting(
    name = "aarch64",
    constraint_values = ["@platforms//cpu:aarch64"],
)

config_setting(
    name = "x86_64",
    constraint_values = ["@platforms//cpu:x86_64"],
)

declare_test_guest_targets(
    base_image_rule = test_guest_base_image,
    variant_macro = test_guest_variant,
)

test_guest_test(
    name = "fedora_podman_smoke",
    size = "enormous",
    command = ["true"],
    image = ":fedora_podman_image",
    tags = ["manual"],
)
