// SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: policy.proto

package policyv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Author-controlled sandbox policy.
//
// This package is the public policy contract used by policy files and SDKs.
// Runtime-derived authority and normalization state live in
// openshell.sandbox.v1 and cannot be supplied through these messages.
type PolicyDocument struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Authored policy schema version. The only supported value is 1.
	Version uint32 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// Filesystem access policy. Absence enables the runtime workdir default;
	// a present empty message explicitly disables that default.
	FilesystemPolicy *FilesystemPolicy `protobuf:"bytes,2,opt,name=filesystem_policy,json=filesystemPolicy,proto3" json:"filesystem_policy,omitempty"`
	// Landlock compatibility policy.
	Landlock *LandlockPolicy `protobuf:"bytes,3,opt,name=landlock,proto3" json:"landlock,omitempty"`
	// Process identity policy.
	Process *ProcessPolicy `protobuf:"bytes,4,opt,name=process,proto3" json:"process,omitempty"`
	// Network rules keyed by stable policy-local name.
	NetworkPolicies map[string]*NetworkPolicyRule `protobuf:"bytes,5,rep,name=network_policies,json=networkPolicies,proto3" json:"network_policies,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Reusable middleware configs keyed by stable policy-local name.
	NetworkMiddlewares map[string]*NetworkMiddleware `protobuf:"bytes,6,rep,name=network_middlewares,json=networkMiddlewares,proto3" json:"network_middlewares,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PolicyDocument) Reset() {
	*x = PolicyDocument{}
	mi := &file_policy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyDocument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyDocument) ProtoMessage() {}

func (x *PolicyDocument) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyDocument.ProtoReflect.Descriptor instead.
func (*PolicyDocument) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{0}
}

func (x *PolicyDocument) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *PolicyDocument) GetFilesystemPolicy() *FilesystemPolicy {
	if x != nil {
		return x.FilesystemPolicy
	}
	return nil
}

func (x *PolicyDocument) GetLandlock() *LandlockPolicy {
	if x != nil {
		return x.Landlock
	}
	return nil
}

func (x *PolicyDocument) GetProcess() *ProcessPolicy {
	if x != nil {
		return x.Process
	}
	return nil
}

func (x *PolicyDocument) GetNetworkPolicies() map[string]*NetworkPolicyRule {
	if x != nil {
		return x.NetworkPolicies
	}
	return nil
}

func (x *PolicyDocument) GetNetworkMiddlewares() map[string]*NetworkMiddleware {
	if x != nil {
		return x.NetworkMiddlewares
	}
	return nil
}

type FilesystemPolicy struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IncludeWorkdir bool                   `protobuf:"varint,1,opt,name=include_workdir,json=includeWorkdir,proto3" json:"include_workdir,omitempty"`
	ReadOnly       []string               `protobuf:"bytes,2,rep,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	ReadWrite      []string               `protobuf:"bytes,3,rep,name=read_write,json=readWrite,proto3" json:"read_write,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FilesystemPolicy) Reset() {
	*x = FilesystemPolicy{}
	mi := &file_policy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilesystemPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesystemPolicy) ProtoMessage() {}

func (x *FilesystemPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesystemPolicy.ProtoReflect.Descriptor instead.
func (*FilesystemPolicy) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{1}
}

func (x *FilesystemPolicy) GetIncludeWorkdir() bool {
	if x != nil {
		return x.IncludeWorkdir
	}
	return false
}

func (x *FilesystemPolicy) GetReadOnly() []string {
	if x != nil {
		return x.ReadOnly
	}
	return nil
}

func (x *FilesystemPolicy) GetReadWrite() []string {
	if x != nil {
		return x.ReadWrite
	}
	return nil
}

type LandlockPolicy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Documented values are "best_effort" and "hard_requirement".
	Compatibility string `protobuf:"bytes,1,opt,name=compatibility,proto3" json:"compatibility,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LandlockPolicy) Reset() {
	*x = LandlockPolicy{}
	mi := &file_policy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LandlockPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LandlockPolicy) ProtoMessage() {}

func (x *LandlockPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LandlockPolicy.ProtoReflect.Descriptor instead.
func (*LandlockPolicy) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{2}
}

func (x *LandlockPolicy) GetCompatibility() string {
	if x != nil {
		return x.Compatibility
	}
	return ""
}

type ProcessPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunAsUser     string                 `protobuf:"bytes,1,opt,name=run_as_user,json=runAsUser,proto3" json:"run_as_user,omitempty"`
	RunAsGroup    string                 `protobuf:"bytes,2,opt,name=run_as_group,json=runAsGroup,proto3" json:"run_as_group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessPolicy) Reset() {
	*x = ProcessPolicy{}
	mi := &file_policy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessPolicy) ProtoMessage() {}

func (x *ProcessPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessPolicy.ProtoReflect.Descriptor instead.
func (*ProcessPolicy) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{3}
}

func (x *ProcessPolicy) GetRunAsUser() string {
	if x != nil {
		return x.RunAsUser
	}
	return ""
}

func (x *ProcessPolicy) GetRunAsGroup() string {
	if x != nil {
		return x.RunAsGroup
	}
	return ""
}

type NetworkPolicyRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Display name. An empty value falls back to the surrounding map key.
	Name      string             `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Endpoints []*NetworkEndpoint `protobuf:"bytes,2,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	// Omitted and empty both match no process.
	Binaries      []*NetworkBinary `protobuf:"bytes,3,rep,name=binaries,proto3" json:"binaries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkPolicyRule) Reset() {
	*x = NetworkPolicyRule{}
	mi := &file_policy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkPolicyRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkPolicyRule) ProtoMessage() {}

func (x *NetworkPolicyRule) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkPolicyRule.ProtoReflect.Descriptor instead.
func (*NetworkPolicyRule) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{4}
}

func (x *NetworkPolicyRule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NetworkPolicyRule) GetEndpoints() []*NetworkEndpoint {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *NetworkPolicyRule) GetBinaries() []*NetworkBinary {
	if x != nil {
		return x.Binaries
	}
	return nil
}

type NetworkEndpoint struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Host        string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Protocol    string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Tls         string                 `protobuf:"bytes,4,opt,name=tls,proto3" json:"tls,omitempty"`
	Enforcement string                 `protobuf:"bytes,5,opt,name=enforcement,proto3" json:"enforcement,omitempty"`
	Access      string                 `protobuf:"bytes,6,opt,name=access,proto3" json:"access,omitempty"`
	Rules       []*L7Rule              `protobuf:"bytes,7,rep,name=rules,proto3" json:"rules,omitempty"`
	AllowedIps  []string               `protobuf:"bytes,8,rep,name=allowed_ips,json=allowedIps,proto3" json:"allowed_ips,omitempty"`
	// Every endpoint has one nonempty, duplicate-free port list. Tag 9 remains
	// stable because earlier review builds exposed this repeated field.
	Ports                        []uint32                     `protobuf:"varint,9,rep,packed,name=ports,proto3" json:"ports,omitempty"`
	DenyRules                    []*L7DenyRule                `protobuf:"bytes,10,rep,name=deny_rules,json=denyRules,proto3" json:"deny_rules,omitempty"`
	AllowEncodedSlash            bool                         `protobuf:"varint,11,opt,name=allow_encoded_slash,json=allowEncodedSlash,proto3" json:"allow_encoded_slash,omitempty"`
	PersistedQueries             string                       `protobuf:"bytes,12,opt,name=persisted_queries,json=persistedQueries,proto3" json:"persisted_queries,omitempty"`
	GraphqlPersistedQueries      map[string]*GraphqlOperation `protobuf:"bytes,13,rep,name=graphql_persisted_queries,json=graphqlPersistedQueries,proto3" json:"graphql_persisted_queries,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	GraphqlMaxBodyBytes          uint32                       `protobuf:"varint,14,opt,name=graphql_max_body_bytes,json=graphqlMaxBodyBytes,proto3" json:"graphql_max_body_bytes,omitempty"`
	Path                         string                       `protobuf:"bytes,15,opt,name=path,proto3" json:"path,omitempty"`
	WebsocketCredentialRewrite   bool                         `protobuf:"varint,16,opt,name=websocket_credential_rewrite,json=websocketCredentialRewrite,proto3" json:"websocket_credential_rewrite,omitempty"`
	RequestBodyCredentialRewrite bool                         `protobuf:"varint,17,opt,name=request_body_credential_rewrite,json=requestBodyCredentialRewrite,proto3" json:"request_body_credential_rewrite,omitempty"`
	CredentialSigning            string                       `protobuf:"bytes,19,opt,name=credential_signing,json=credentialSigning,proto3" json:"credential_signing,omitempty"`
	SigningService               string                       `protobuf:"bytes,20,opt,name=signing_service,json=signingService,proto3" json:"signing_service,omitempty"`
	SigningRegion                string                       `protobuf:"bytes,21,opt,name=signing_region,json=signingRegion,proto3" json:"signing_region,omitempty"`
	JsonRpc                      *JsonRpcConfig               `protobuf:"bytes,22,opt,name=json_rpc,json=jsonRpc,proto3" json:"json_rpc,omitempty"`
	Mcp                          *McpConfig                   `protobuf:"bytes,23,opt,name=mcp,proto3" json:"mcp,omitempty"`
	CredentialBinding            *NetworkCredentialBinding    `protobuf:"bytes,24,opt,name=credential_binding,json=credentialBinding,proto3" json:"credential_binding,omitempty"`
	AllowUninspectedCredentials  bool                         `protobuf:"varint,25,opt,name=allow_uninspected_credentials,json=allowUninspectedCredentials,proto3" json:"allow_uninspected_credentials,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *NetworkEndpoint) Reset() {
	*x = NetworkEndpoint{}
	mi := &file_policy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkEndpoint) ProtoMessage() {}

func (x *NetworkEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkEndpoint.ProtoReflect.Descriptor instead.
func (*NetworkEndpoint) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{5}
}

func (x *NetworkEndpoint) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *NetworkEndpoint) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *NetworkEndpoint) GetTls() string {
	if x != nil {
		return x.Tls
	}
	return ""
}

func (x *NetworkEndpoint) GetEnforcement() string {
	if x != nil {
		return x.Enforcement
	}
	return ""
}

func (x *NetworkEndpoint) GetAccess() string {
	if x != nil {
		return x.Access
	}
	return ""
}

func (x *NetworkEndpoint) GetRules() []*L7Rule {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *NetworkEndpoint) GetAllowedIps() []string {
	if x != nil {
		return x.AllowedIps
	}
	return nil
}

func (x *NetworkEndpoint) GetPorts() []uint32 {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *NetworkEndpoint) GetDenyRules() []*L7DenyRule {
	if x != nil {
		return x.DenyRules
	}
	return nil
}

func (x *NetworkEndpoint) GetAllowEncodedSlash() bool {
	if x != nil {
		return x.AllowEncodedSlash
	}
	return false
}

func (x *NetworkEndpoint) GetPersistedQueries() string {
	if x != nil {
		return x.PersistedQueries
	}
	return ""
}

func (x *NetworkEndpoint) GetGraphqlPersistedQueries() map[string]*GraphqlOperation {
	if x != nil {
		return x.GraphqlPersistedQueries
	}
	return nil
}

func (x *NetworkEndpoint) GetGraphqlMaxBodyBytes() uint32 {
	if x != nil {
		return x.GraphqlMaxBodyBytes
	}
	return 0
}

func (x *NetworkEndpoint) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *NetworkEndpoint) GetWebsocketCredentialRewrite() bool {
	if x != nil {
		return x.WebsocketCredentialRewrite
	}
	return false
}

func (x *NetworkEndpoint) GetRequestBodyCredentialRewrite() bool {
	if x != nil {
		return x.RequestBodyCredentialRewrite
	}
	return false
}

func (x *NetworkEndpoint) GetCredentialSigning() string {
	if x != nil {
		return x.CredentialSigning
	}
	return ""
}

func (x *NetworkEndpoint) GetSigningService() string {
	if x != nil {
		return x.SigningService
	}
	return ""
}

func (x *NetworkEndpoint) GetSigningRegion() string {
	if x != nil {
		return x.SigningRegion
	}
	return ""
}

func (x *NetworkEndpoint) GetJsonRpc() *JsonRpcConfig {
	if x != nil {
		return x.JsonRpc
	}
	return nil
}

func (x *NetworkEndpoint) GetMcp() *McpConfig {
	if x != nil {
		return x.Mcp
	}
	return nil
}

func (x *NetworkEndpoint) GetCredentialBinding() *NetworkCredentialBinding {
	if x != nil {
		return x.CredentialBinding
	}
	return nil
}

func (x *NetworkEndpoint) GetAllowUninspectedCredentials() bool {
	if x != nil {
		return x.AllowUninspectedCredentials
	}
	return false
}

type NetworkCredentialBinding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkCredentialBinding) Reset() {
	*x = NetworkCredentialBinding{}
	mi := &file_policy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkCredentialBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkCredentialBinding) ProtoMessage() {}

func (x *NetworkCredentialBinding) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkCredentialBinding.ProtoReflect.Descriptor instead.
func (*NetworkCredentialBinding) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{6}
}

func (x *NetworkCredentialBinding) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

type JsonRpcConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxBodyBytes  uint32                 `protobuf:"varint,1,opt,name=max_body_bytes,json=maxBodyBytes,proto3" json:"max_body_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JsonRpcConfig) Reset() {
	*x = JsonRpcConfig{}
	mi := &file_policy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JsonRpcConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsonRpcConfig) ProtoMessage() {}

func (x *JsonRpcConfig) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsonRpcConfig.ProtoReflect.Descriptor instead.
func (*JsonRpcConfig) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{7}
}

func (x *JsonRpcConfig) GetMaxBodyBytes() uint32 {
	if x != nil {
		return x.MaxBodyBytes
	}
	return 0
}

type McpConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Empty and omitted are equivalent in protobuf and select the pinned
	// default revision. Nonempty values form an exact allowlist.
	Versions                []string `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions,omitempty"`
	MaxBodyBytes            uint32   `protobuf:"varint,2,opt,name=max_body_bytes,json=maxBodyBytes,proto3" json:"max_body_bytes,omitempty"`
	StrictToolNames         *bool    `protobuf:"varint,3,opt,name=strict_tool_names,json=strictToolNames,proto3,oneof" json:"strict_tool_names,omitempty"`
	AllowAllKnownMcpMethods *bool    `protobuf:"varint,4,opt,name=allow_all_known_mcp_methods,json=allowAllKnownMcpMethods,proto3,oneof" json:"allow_all_known_mcp_methods,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *McpConfig) Reset() {
	*x = McpConfig{}
	mi := &file_policy_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *McpConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*McpConfig) ProtoMessage() {}

func (x *McpConfig) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use McpConfig.ProtoReflect.Descriptor instead.
func (*McpConfig) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{8}
}

func (x *McpConfig) GetVersions() []string {
	if x != nil {
		return x.Versions
	}
	return nil
}

func (x *McpConfig) GetMaxBodyBytes() uint32 {
	if x != nil {
		return x.MaxBodyBytes
	}
	return 0
}

func (x *McpConfig) GetStrictToolNames() bool {
	if x != nil && x.StrictToolNames != nil {
		return *x.StrictToolNames
	}
	return false
}

func (x *McpConfig) GetAllowAllKnownMcpMethods() bool {
	if x != nil && x.AllowAllKnownMcpMethods != nil {
		return *x.AllowAllKnownMcpMethods
	}
	return false
}

type GraphqlOperation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationType string                 `protobuf:"bytes,1,opt,name=operation_type,json=operationType,proto3" json:"operation_type,omitempty"`
	OperationName string                 `protobuf:"bytes,2,opt,name=operation_name,json=operationName,proto3" json:"operation_name,omitempty"`
	Fields        []string               `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphqlOperation) Reset() {
	*x = GraphqlOperation{}
	mi := &file_policy_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphqlOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphqlOperation) ProtoMessage() {}

func (x *GraphqlOperation) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphqlOperation.ProtoReflect.Descriptor instead.
func (*GraphqlOperation) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{9}
}

func (x *GraphqlOperation) GetOperationType() string {
	if x != nil {
		return x.OperationType
	}
	return ""
}

func (x *GraphqlOperation) GetOperationName() string {
	if x != nil {
		return x.OperationName
	}
	return ""
}

func (x *GraphqlOperation) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type L7Rule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allow         *L7Allow               `protobuf:"bytes,1,opt,name=allow,proto3" json:"allow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L7Rule) Reset() {
	*x = L7Rule{}
	mi := &file_policy_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L7Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L7Rule) ProtoMessage() {}

func (x *L7Rule) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L7Rule.ProtoReflect.Descriptor instead.
func (*L7Rule) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{10}
}

func (x *L7Rule) GetAllow() *L7Allow {
	if x != nil {
		return x.Allow
	}
	return nil
}

type L7Allow struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Method        string                       `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                       `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Command       string                       `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	Query         map[string]*Matcher          `protobuf:"bytes,4,rep,name=query,proto3" json:"query,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	OperationType string                       `protobuf:"bytes,5,opt,name=operation_type,json=operationType,proto3" json:"operation_type,omitempty"`
	OperationName string                       `protobuf:"bytes,6,opt,name=operation_name,json=operationName,proto3" json:"operation_name,omitempty"`
	Fields        []string                     `protobuf:"bytes,7,rep,name=fields,proto3" json:"fields,omitempty"`
	Tool          *Matcher                     `protobuf:"bytes,8,opt,name=tool,proto3" json:"tool,omitempty"`
	Params        map[string]*ParameterMatcher `protobuf:"bytes,9,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L7Allow) Reset() {
	*x = L7Allow{}
	mi := &file_policy_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L7Allow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L7Allow) ProtoMessage() {}

func (x *L7Allow) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L7Allow.ProtoReflect.Descriptor instead.
func (*L7Allow) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{11}
}

func (x *L7Allow) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *L7Allow) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *L7Allow) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *L7Allow) GetQuery() map[string]*Matcher {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *L7Allow) GetOperationType() string {
	if x != nil {
		return x.OperationType
	}
	return ""
}

func (x *L7Allow) GetOperationName() string {
	if x != nil {
		return x.OperationName
	}
	return ""
}

func (x *L7Allow) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *L7Allow) GetTool() *Matcher {
	if x != nil {
		return x.Tool
	}
	return nil
}

func (x *L7Allow) GetParams() map[string]*ParameterMatcher {
	if x != nil {
		return x.Params
	}
	return nil
}

type L7DenyRule struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Method        string                       `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                       `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Command       string                       `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	Query         map[string]*Matcher          `protobuf:"bytes,4,rep,name=query,proto3" json:"query,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	OperationType string                       `protobuf:"bytes,5,opt,name=operation_type,json=operationType,proto3" json:"operation_type,omitempty"`
	OperationName string                       `protobuf:"bytes,6,opt,name=operation_name,json=operationName,proto3" json:"operation_name,omitempty"`
	Fields        []string                     `protobuf:"bytes,7,rep,name=fields,proto3" json:"fields,omitempty"`
	Tool          *Matcher                     `protobuf:"bytes,8,opt,name=tool,proto3" json:"tool,omitempty"`
	Params        map[string]*ParameterMatcher `protobuf:"bytes,9,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L7DenyRule) Reset() {
	*x = L7DenyRule{}
	mi := &file_policy_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L7DenyRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L7DenyRule) ProtoMessage() {}

func (x *L7DenyRule) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L7DenyRule.ProtoReflect.Descriptor instead.
func (*L7DenyRule) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{12}
}

func (x *L7DenyRule) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *L7DenyRule) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *L7DenyRule) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *L7DenyRule) GetQuery() map[string]*Matcher {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *L7DenyRule) GetOperationType() string {
	if x != nil {
		return x.OperationType
	}
	return ""
}

func (x *L7DenyRule) GetOperationName() string {
	if x != nil {
		return x.OperationName
	}
	return ""
}

func (x *L7DenyRule) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *L7DenyRule) GetTool() *Matcher {
	if x != nil {
		return x.Tool
	}
	return nil
}

func (x *L7DenyRule) GetParams() map[string]*ParameterMatcher {
	if x != nil {
		return x.Params
	}
	return nil
}

type Matcher struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Matcher_Glob
	//	*Matcher_Any
	Kind          isMatcher_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Matcher) Reset() {
	*x = Matcher{}
	mi := &file_policy_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Matcher) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Matcher) ProtoMessage() {}

func (x *Matcher) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Matcher.ProtoReflect.Descriptor instead.
func (*Matcher) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{13}
}

func (x *Matcher) GetKind() isMatcher_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Matcher) GetGlob() string {
	if x != nil {
		if x, ok := x.Kind.(*Matcher_Glob); ok {
			return x.Glob
		}
	}
	return ""
}

func (x *Matcher) GetAny() *AnyMatcher {
	if x != nil {
		if x, ok := x.Kind.(*Matcher_Any); ok {
			return x.Any
		}
	}
	return nil
}

type isMatcher_Kind interface {
	isMatcher_Kind()
}

type Matcher_Glob struct {
	Glob string `protobuf:"bytes,1,opt,name=glob,proto3,oneof"`
}

type Matcher_Any struct {
	Any *AnyMatcher `protobuf:"bytes,2,opt,name=any,proto3,oneof"`
}

func (*Matcher_Glob) isMatcher_Kind() {}

func (*Matcher_Any) isMatcher_Kind() {}

type AnyMatcher struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnyMatcher) Reset() {
	*x = AnyMatcher{}
	mi := &file_policy_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnyMatcher) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnyMatcher) ProtoMessage() {}

func (x *AnyMatcher) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnyMatcher.ProtoReflect.Descriptor instead.
func (*AnyMatcher) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{14}
}

func (x *AnyMatcher) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type ParameterMatcher struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*ParameterMatcher_Matcher
	//	*ParameterMatcher_Object
	Kind          isParameterMatcher_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParameterMatcher) Reset() {
	*x = ParameterMatcher{}
	mi := &file_policy_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParameterMatcher) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParameterMatcher) ProtoMessage() {}

func (x *ParameterMatcher) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParameterMatcher.ProtoReflect.Descriptor instead.
func (*ParameterMatcher) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{15}
}

func (x *ParameterMatcher) GetKind() isParameterMatcher_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *ParameterMatcher) GetMatcher() *Matcher {
	if x != nil {
		if x, ok := x.Kind.(*ParameterMatcher_Matcher); ok {
			return x.Matcher
		}
	}
	return nil
}

func (x *ParameterMatcher) GetObject() *ParameterObject {
	if x != nil {
		if x, ok := x.Kind.(*ParameterMatcher_Object); ok {
			return x.Object
		}
	}
	return nil
}

type isParameterMatcher_Kind interface {
	isParameterMatcher_Kind()
}

type ParameterMatcher_Matcher struct {
	Matcher *Matcher `protobuf:"bytes,1,opt,name=matcher,proto3,oneof"`
}

type ParameterMatcher_Object struct {
	Object *ParameterObject `protobuf:"bytes,2,opt,name=object,proto3,oneof"`
}

func (*ParameterMatcher_Matcher) isParameterMatcher_Kind() {}

func (*ParameterMatcher_Object) isParameterMatcher_Kind() {}

type ParameterObject struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Fields        map[string]*ParameterMatcher `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParameterObject) Reset() {
	*x = ParameterObject{}
	mi := &file_policy_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParameterObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParameterObject) ProtoMessage() {}

func (x *ParameterObject) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParameterObject.ProtoReflect.Descriptor instead.
func (*ParameterObject) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{16}
}

func (x *ParameterObject) GetFields() map[string]*ParameterMatcher {
	if x != nil {
		return x.Fields
	}
	return nil
}

type NetworkBinary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkBinary) Reset() {
	*x = NetworkBinary{}
	mi := &file_policy_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkBinary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkBinary) ProtoMessage() {}

func (x *NetworkBinary) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkBinary.ProtoReflect.Descriptor instead.
func (*NetworkBinary) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{17}
}

func (x *NetworkBinary) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type NetworkMiddleware struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Display name. An empty value falls back to the surrounding map key.
	Name          string                      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Middleware    string                      `protobuf:"bytes,2,opt,name=middleware,proto3" json:"middleware,omitempty"`
	Config        *structpb.Struct            `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	OnError       string                      `protobuf:"bytes,4,opt,name=on_error,json=onError,proto3" json:"on_error,omitempty"`
	Endpoints     *MiddlewareEndpointSelector `protobuf:"bytes,5,opt,name=endpoints,proto3" json:"endpoints,omitempty"`
	Order         int32                       `protobuf:"varint,6,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkMiddleware) Reset() {
	*x = NetworkMiddleware{}
	mi := &file_policy_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkMiddleware) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkMiddleware) ProtoMessage() {}

func (x *NetworkMiddleware) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkMiddleware.ProtoReflect.Descriptor instead.
func (*NetworkMiddleware) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{18}
}

func (x *NetworkMiddleware) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NetworkMiddleware) GetMiddleware() string {
	if x != nil {
		return x.Middleware
	}
	return ""
}

func (x *NetworkMiddleware) GetConfig() *structpb.Struct {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *NetworkMiddleware) GetOnError() string {
	if x != nil {
		return x.OnError
	}
	return ""
}

func (x *NetworkMiddleware) GetEndpoints() *MiddlewareEndpointSelector {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *NetworkMiddleware) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

type MiddlewareEndpointSelector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Include       []string               `protobuf:"bytes,1,rep,name=include,proto3" json:"include,omitempty"`
	Exclude       []string               `protobuf:"bytes,2,rep,name=exclude,proto3" json:"exclude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MiddlewareEndpointSelector) Reset() {
	*x = MiddlewareEndpointSelector{}
	mi := &file_policy_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MiddlewareEndpointSelector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MiddlewareEndpointSelector) ProtoMessage() {}

func (x *MiddlewareEndpointSelector) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MiddlewareEndpointSelector.ProtoReflect.Descriptor instead.
func (*MiddlewareEndpointSelector) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{19}
}

func (x *MiddlewareEndpointSelector) GetInclude() []string {
	if x != nil {
		return x.Include
	}
	return nil
}

func (x *MiddlewareEndpointSelector) GetExclude() []string {
	if x != nil {
		return x.Exclude
	}
	return nil
}

var File_policy_proto protoreflect.FileDescriptor

const file_policy_proto_rawDesc = "" +
	"\n" +
	"\fpolicy.proto\x12\x13openshell.policy.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1bbuf/validate/validate.proto\"\xdd\x05\n" +
	"\x0ePolicyDocument\x12!\n" +
	"\aversion\x18\x01 \x01(\rB\a\xbaH\x04*\x02\b\x01R\aversion\x12R\n" +
	"\x11filesystem_policy\x18\x02 \x01(\v2%.openshell.policy.v1.FilesystemPolicyR\x10filesystemPolicy\x12?\n" +
	"\blandlock\x18\x03 \x01(\v2#.openshell.policy.v1.LandlockPolicyR\blandlock\x12<\n" +
	"\aprocess\x18\x04 \x01(\v2\".openshell.policy.v1.ProcessPolicyR\aprocess\x12w\n" +
	"\x10network_policies\x18\x05 \x03(\v28.openshell.policy.v1.PolicyDocument.NetworkPoliciesEntryB\x12\xbaH\x0f\x9a\x01\f\x10\x80\b\"\ar\x05\x10\x01\x18\x80\x02R\x0fnetworkPolicies\x12\x80\x01\n" +
	"\x13network_middlewares\x18\x06 \x03(\v2;.openshell.policy.v1.PolicyDocument.NetworkMiddlewaresEntryB\x12\xbaH\x0f\x9a\x01\f\x10\x80\b\"\ar\x05\x10\x01\x18\x80\x02R\x12networkMiddlewares\x1aj\n" +
	"\x14NetworkPoliciesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12<\n" +
	"\x05value\x18\x02 \x01(\v2&.openshell.policy.v1.NetworkPolicyRuleR\x05value:\x028\x01\x1am\n" +
	"\x17NetworkMiddlewaresEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12<\n" +
	"\x05value\x18\x02 \x01(\v2&.openshell.policy.v1.NetworkMiddlewareR\x05value:\x028\x01\"w\n" +
	"\x10FilesystemPolicy\x12'\n" +
	"\x0finclude_workdir\x18\x01 \x01(\bR\x0eincludeWorkdir\x12\x1b\n" +
	"\tread_only\x18\x02 \x03(\tR\breadOnly\x12\x1d\n" +
	"\n" +
	"read_write\x18\x03 \x03(\tR\treadWrite\"6\n" +
	"\x0eLandlockPolicy\x12$\n" +
	"\rcompatibility\x18\x01 \x01(\tR\rcompatibility\"Q\n" +
	"\rProcessPolicy\x12\x1e\n" +
	"\vrun_as_user\x18\x01 \x01(\tR\trunAsUser\x12 \n" +
	"\frun_as_group\x18\x02 \x01(\tR\n" +
	"runAsGroup\"\xc1\x01\n" +
	"\x11NetworkPolicyRule\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12M\n" +
	"\tendpoints\x18\x02 \x03(\v2$.openshell.policy.v1.NetworkEndpointB\t\xbaH\x06\x92\x01\x03\x10\x80 R\tendpoints\x12I\n" +
	"\bbinaries\x18\x03 \x03(\v2\".openshell.policy.v1.NetworkBinaryB\t\xbaH\x06\x92\x01\x03\x10\x80 R\bbinaries\"\xfb\n" +
	"\n" +
	"\x0fNetworkEndpoint\x12\x1c\n" +
	"\x04host\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x18\x80 R\x04host\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\x12\x10\n" +
	"\x03tls\x18\x04 \x01(\tR\x03tls\x12 \n" +
	"\venforcement\x18\x05 \x01(\tR\venforcement\x12\x16\n" +
	"\x06access\x18\x06 \x01(\tR\x06access\x12=\n" +
	"\x05rules\x18\a \x03(\v2\x1b.openshell.policy.v1.L7RuleB\n" +
	"\xbaH\a\x92\x01\x04\x10\x80\x80\x01R\x05rules\x123\n" +
	"\vallowed_ips\x18\b \x03(\tB\x12\xbaH\x0f\x92\x01\f\x10\x80 \"\ar\x05\x10\x01\x18\x80 R\n" +
	"allowedIps\x12.\n" +
	"\x05ports\x18\t \x03(\rB\x18\xbaH\x15\x92\x01\x12\b\x01\x10\xff\xff\x03\x18\x01\"\b*\x06\x18\xff\xff\x03(\x01R\x05ports\x12J\n" +
	"\n" +
	"deny_rules\x18\n" +
	" \x03(\v2\x1f.openshell.policy.v1.L7DenyRuleB\n" +
	"\xbaH\a\x92\x01\x04\x10\x80\x80\x01R\tdenyRules\x12.\n" +
	"\x13allow_encoded_slash\x18\v \x01(\bR\x11allowEncodedSlash\x12+\n" +
	"\x11persisted_queries\x18\f \x01(\tR\x10persistedQueries\x12}\n" +
	"\x19graphql_persisted_queries\x18\r \x03(\v2A.openshell.policy.v1.NetworkEndpoint.GraphqlPersistedQueriesEntryR\x17graphqlPersistedQueries\x123\n" +
	"\x16graphql_max_body_bytes\x18\x0e \x01(\rR\x13graphqlMaxBodyBytes\x12\x12\n" +
	"\x04path\x18\x0f \x01(\tR\x04path\x12@\n" +
	"\x1cwebsocket_credential_rewrite\x18\x10 \x01(\bR\x1awebsocketCredentialRewrite\x12E\n" +
	"\x1frequest_body_credential_rewrite\x18\x11 \x01(\bR\x1crequestBodyCredentialRewrite\x12-\n" +
	"\x12credential_signing\x18\x13 \x01(\tR\x11credentialSigning\x12'\n" +
	"\x0fsigning_service\x18\x14 \x01(\tR\x0esigningService\x12%\n" +
	"\x0esigning_region\x18\x15 \x01(\tR\rsigningRegion\x12=\n" +
	"\bjson_rpc\x18\x16 \x01(\v2\".openshell.policy.v1.JsonRpcConfigR\ajsonRpc\x120\n" +
	"\x03mcp\x18\x17 \x01(\v2\x1e.openshell.policy.v1.McpConfigR\x03mcp\x12\\\n" +
	"\x12credential_binding\x18\x18 \x01(\v2-.openshell.policy.v1.NetworkCredentialBindingR\x11credentialBinding\x12B\n" +
	"\x1dallow_uninspected_credentials\x18\x19 \x01(\bR\x1ballowUninspectedCredentials\x1aq\n" +
	"\x1cGraphqlPersistedQueriesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12;\n" +
	"\x05value\x18\x02 \x01(\v2%.openshell.policy.v1.GraphqlOperationR\x05value:\x028\x01J\x04\b\x02\x10\x03J\x04\b\x12\x10\x13J\x04\b\x1a\x10\x1bR\x04portR\x10advisor_proposedR\x15provider_credentialed\"6\n" +
	"\x18NetworkCredentialBinding\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\"5\n" +
	"\rJsonRpcConfig\x12$\n" +
	"\x0emax_body_bytes\x18\x01 \x01(\rR\fmaxBodyBytes\"\xf7\x01\n" +
	"\tMcpConfig\x12\x1a\n" +
	"\bversions\x18\x01 \x03(\tR\bversions\x12$\n" +
	"\x0emax_body_bytes\x18\x02 \x01(\rR\fmaxBodyBytes\x12/\n" +
	"\x11strict_tool_names\x18\x03 \x01(\bH\x00R\x0fstrictToolNames\x88\x01\x01\x12A\n" +
	"\x1ballow_all_known_mcp_methods\x18\x04 \x01(\bH\x01R\x17allowAllKnownMcpMethods\x88\x01\x01B\x14\n" +
	"\x12_strict_tool_namesB\x1e\n" +
	"\x1c_allow_all_known_mcp_methods\"x\n" +
	"\x10GraphqlOperation\x12%\n" +
	"\x0eoperation_type\x18\x01 \x01(\tR\roperationType\x12%\n" +
	"\x0eoperation_name\x18\x02 \x01(\tR\roperationName\x12\x16\n" +
	"\x06fields\x18\x03 \x03(\tR\x06fields\"D\n" +
	"\x06L7Rule\x12:\n" +
	"\x05allow\x18\x01 \x01(\v2\x1c.openshell.policy.v1.L7AllowB\x06\xbaH\x03\xc8\x01\x01R\x05allow\"\xa2\x04\n" +
	"\aL7Allow\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\x12=\n" +
	"\x05query\x18\x04 \x03(\v2'.openshell.policy.v1.L7Allow.QueryEntryR\x05query\x12%\n" +
	"\x0eoperation_type\x18\x05 \x01(\tR\roperationType\x12%\n" +
	"\x0eoperation_name\x18\x06 \x01(\tR\roperationName\x12\x16\n" +
	"\x06fields\x18\a \x03(\tR\x06fields\x120\n" +
	"\x04tool\x18\b \x01(\v2\x1c.openshell.policy.v1.MatcherR\x04tool\x12@\n" +
	"\x06params\x18\t \x03(\v2(.openshell.policy.v1.L7Allow.ParamsEntryR\x06params\x1aV\n" +
	"\n" +
	"QueryEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.openshell.policy.v1.MatcherR\x05value:\x028\x01\x1a`\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12;\n" +
	"\x05value\x18\x02 \x01(\v2%.openshell.policy.v1.ParameterMatcherR\x05value:\x028\x01\"\xab\x04\n" +
	"\n" +
	"L7DenyRule\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\x12@\n" +
	"\x05query\x18\x04 \x03(\v2*.openshell.policy.v1.L7DenyRule.QueryEntryR\x05query\x12%\n" +
	"\x0eoperation_type\x18\x05 \x01(\tR\roperationType\x12%\n" +
	"\x0eoperation_name\x18\x06 \x01(\tR\roperationName\x12\x16\n" +
	"\x06fields\x18\a \x03(\tR\x06fields\x120\n" +
	"\x04tool\x18\b \x01(\v2\x1c.openshell.policy.v1.MatcherR\x04tool\x12C\n" +
	"\x06params\x18\t \x03(\v2+.openshell.policy.v1.L7DenyRule.ParamsEntryR\x06params\x1aV\n" +
	"\n" +
	"QueryEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.openshell.policy.v1.MatcherR\x05value:\x028\x01\x1a`\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12;\n" +
	"\x05value\x18\x02 \x01(\v2%.openshell.policy.v1.ParameterMatcherR\x05value:\x028\x01\"o\n" +
	"\aMatcher\x12 \n" +
	"\x04glob\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80 H\x00R\x04glob\x123\n" +
	"\x03any\x18\x02 \x01(\v2\x1f.openshell.policy.v1.AnyMatcherH\x00R\x03anyB\r\n" +
	"\x04kind\x12\x05\xbaH\x02\b\x01\"<\n" +
	"\n" +
	"AnyMatcher\x12.\n" +
	"\x06values\x18\x01 \x03(\tB\x16\xbaH\x13\x92\x01\x10\b\x01\x10\x80\b\x18\x01\"\ar\x05\x10\x01\x18\x80 R\x06values\"\x9b\x01\n" +
	"\x10ParameterMatcher\x128\n" +
	"\amatcher\x18\x01 \x01(\v2\x1c.openshell.policy.v1.MatcherH\x00R\amatcher\x12>\n" +
	"\x06object\x18\x02 \x01(\v2$.openshell.policy.v1.ParameterObjectH\x00R\x06objectB\r\n" +
	"\x04kind\x12\x05\xbaH\x02\b\x01\"\xd3\x01\n" +
	"\x0fParameterObject\x12^\n" +
	"\x06fields\x18\x01 \x03(\v20.openshell.policy.v1.ParameterObject.FieldsEntryB\x14\xbaH\x11\x9a\x01\x0e\b\x01\x10\x80\b\"\ar\x05\x10\x01\x18\x80\x02R\x06fields\x1a`\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12;\n" +
	"\x05value\x18\x02 \x01(\v2%.openshell.policy.v1.ParameterMatcherR\x05value:\x028\x01\"/\n" +
	"\rNetworkBinary\x12\x1e\n" +
	"\x04path\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80 R\x04path\"\xf8\x01\n" +
	"\x11NetworkMiddleware\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"middleware\x18\x02 \x01(\tR\n" +
	"middleware\x12/\n" +
	"\x06config\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x06config\x12\x19\n" +
	"\bon_error\x18\x04 \x01(\tR\aonError\x12M\n" +
	"\tendpoints\x18\x05 \x01(\v2/.openshell.policy.v1.MiddlewareEndpointSelectorR\tendpoints\x12\x14\n" +
	"\x05order\x18\x06 \x01(\x05R\x05order\"P\n" +
	"\x1aMiddlewareEndpointSelector\x12\x18\n" +
	"\ainclude\x18\x01 \x03(\tR\ainclude\x12\x18\n" +
	"\aexclude\x18\x02 \x03(\tR\aexcludeb\x06proto3"

var (
	file_policy_proto_rawDescOnce sync.Once
	file_policy_proto_rawDescData []byte
)

func file_policy_proto_rawDescGZIP() []byte {
	file_policy_proto_rawDescOnce.Do(func() {
		file_policy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_policy_proto_rawDesc), len(file_policy_proto_rawDesc)))
	})
	return file_policy_proto_rawDescData
}

var file_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_policy_proto_goTypes = []any{
	(*PolicyDocument)(nil),             // 0: openshell.policy.v1.PolicyDocument
	(*FilesystemPolicy)(nil),           // 1: openshell.policy.v1.FilesystemPolicy
	(*LandlockPolicy)(nil),             // 2: openshell.policy.v1.LandlockPolicy
	(*ProcessPolicy)(nil),              // 3: openshell.policy.v1.ProcessPolicy
	(*NetworkPolicyRule)(nil),          // 4: openshell.policy.v1.NetworkPolicyRule
	(*NetworkEndpoint)(nil),            // 5: openshell.policy.v1.NetworkEndpoint
	(*NetworkCredentialBinding)(nil),   // 6: openshell.policy.v1.NetworkCredentialBinding
	(*JsonRpcConfig)(nil),              // 7: openshell.policy.v1.JsonRpcConfig
	(*McpConfig)(nil),                  // 8: openshell.policy.v1.McpConfig
	(*GraphqlOperation)(nil),           // 9: openshell.policy.v1.GraphqlOperation
	(*L7Rule)(nil),                     // 10: openshell.policy.v1.L7Rule
	(*L7Allow)(nil),                    // 11: openshell.policy.v1.L7Allow
	(*L7DenyRule)(nil),                 // 12: openshell.policy.v1.L7DenyRule
	(*Matcher)(nil),                    // 13: openshell.policy.v1.Matcher
	(*AnyMatcher)(nil),                 // 14: openshell.policy.v1.AnyMatcher
	(*ParameterMatcher)(nil),           // 15: openshell.policy.v1.ParameterMatcher
	(*ParameterObject)(nil),            // 16: openshell.policy.v1.ParameterObject
	(*NetworkBinary)(nil),              // 17: openshell.policy.v1.NetworkBinary
	(*NetworkMiddleware)(nil),          // 18: openshell.policy.v1.NetworkMiddleware
	(*MiddlewareEndpointSelector)(nil), // 19: openshell.policy.v1.MiddlewareEndpointSelector
	nil,                                // 20: openshell.policy.v1.PolicyDocument.NetworkPoliciesEntry
	nil,                                // 21: openshell.policy.v1.PolicyDocument.NetworkMiddlewaresEntry
	nil,                                // 22: openshell.policy.v1.NetworkEndpoint.GraphqlPersistedQueriesEntry
	nil,                                // 23: openshell.policy.v1.L7Allow.QueryEntry
	nil,                                // 24: openshell.policy.v1.L7Allow.ParamsEntry
	nil,                                // 25: openshell.policy.v1.L7DenyRule.QueryEntry
	nil,                                // 26: openshell.policy.v1.L7DenyRule.ParamsEntry
	nil,                                // 27: openshell.policy.v1.ParameterObject.FieldsEntry
	(*structpb.Struct)(nil),            // 28: google.protobuf.Struct
}
var file_policy_proto_depIdxs = []int32{
	1,  // 0: openshell.policy.v1.PolicyDocument.filesystem_policy:type_name -> openshell.policy.v1.FilesystemPolicy
	2,  // 1: openshell.policy.v1.PolicyDocument.landlock:type_name -> openshell.policy.v1.LandlockPolicy
	3,  // 2: openshell.policy.v1.PolicyDocument.process:type_name -> openshell.policy.v1.ProcessPolicy
	20, // 3: openshell.policy.v1.PolicyDocument.network_policies:type_name -> openshell.policy.v1.PolicyDocument.NetworkPoliciesEntry
	21, // 4: openshell.policy.v1.PolicyDocument.network_middlewares:type_name -> openshell.policy.v1.PolicyDocument.NetworkMiddlewaresEntry
	5,  // 5: openshell.policy.v1.NetworkPolicyRule.endpoints:type_name -> openshell.policy.v1.NetworkEndpoint
	17, // 6: openshell.policy.v1.NetworkPolicyRule.binaries:type_name -> openshell.policy.v1.NetworkBinary
	10, // 7: openshell.policy.v1.NetworkEndpoint.rules:type_name -> openshell.policy.v1.L7Rule
	12, // 8: openshell.policy.v1.NetworkEndpoint.deny_rules:type_name -> openshell.policy.v1.L7DenyRule
	22, // 9: openshell.policy.v1.NetworkEndpoint.graphql_persisted_queries:type_name -> openshell.policy.v1.NetworkEndpoint.GraphqlPersistedQueriesEntry
	7,  // 10: openshell.policy.v1.NetworkEndpoint.json_rpc:type_name -> openshell.policy.v1.JsonRpcConfig
	8,  // 11: openshell.policy.v1.NetworkEndpoint.mcp:type_name -> openshell.policy.v1.McpConfig
	6,  // 12: openshell.policy.v1.NetworkEndpoint.credential_binding:type_name -> openshell.policy.v1.NetworkCredentialBinding
	11, // 13: openshell.policy.v1.L7Rule.allow:type_name -> openshell.policy.v1.L7Allow
	23, // 14: openshell.policy.v1.L7Allow.query:type_name -> openshell.policy.v1.L7Allow.QueryEntry
	13, // 15: openshell.policy.v1.L7Allow.tool:type_name -> openshell.policy.v1.Matcher
	24, // 16: openshell.policy.v1.L7Allow.params:type_name -> openshell.policy.v1.L7Allow.ParamsEntry
	25, // 17: openshell.policy.v1.L7DenyRule.query:type_name -> openshell.policy.v1.L7DenyRule.QueryEntry
	13, // 18: openshell.policy.v1.L7DenyRule.tool:type_name -> openshell.policy.v1.Matcher
	26, // 19: openshell.policy.v1.L7DenyRule.params:type_name -> openshell.policy.v1.L7DenyRule.ParamsEntry
	14, // 20: openshell.policy.v1.Matcher.any:type_name -> openshell.policy.v1.AnyMatcher
	13, // 21: openshell.policy.v1.ParameterMatcher.matcher:type_name -> openshell.policy.v1.Matcher
	16, // 22: openshell.policy.v1.ParameterMatcher.object:type_name -> openshell.policy.v1.ParameterObject
	27, // 23: openshell.policy.v1.ParameterObject.fields:type_name -> openshell.policy.v1.ParameterObject.FieldsEntry
	28, // 24: openshell.policy.v1.NetworkMiddleware.config:type_name -> google.protobuf.Struct
	19, // 25: openshell.policy.v1.NetworkMiddleware.endpoints:type_name -> openshell.policy.v1.MiddlewareEndpointSelector
	4,  // 26: openshell.policy.v1.PolicyDocument.NetworkPoliciesEntry.value:type_name -> openshell.policy.v1.NetworkPolicyRule
	18, // 27: openshell.policy.v1.PolicyDocument.NetworkMiddlewaresEntry.value:type_name -> openshell.policy.v1.NetworkMiddleware
	9,  // 28: openshell.policy.v1.NetworkEndpoint.GraphqlPersistedQueriesEntry.value:type_name -> openshell.policy.v1.GraphqlOperation
	13, // 29: openshell.policy.v1.L7Allow.QueryEntry.value:type_name -> openshell.policy.v1.Matcher
	15, // 30: openshell.policy.v1.L7Allow.ParamsEntry.value:type_name -> openshell.policy.v1.ParameterMatcher
	13, // 31: openshell.policy.v1.L7DenyRule.QueryEntry.value:type_name -> openshell.policy.v1.Matcher
	15, // 32: openshell.policy.v1.L7DenyRule.ParamsEntry.value:type_name -> openshell.policy.v1.ParameterMatcher
	15, // 33: openshell.policy.v1.ParameterObject.FieldsEntry.value:type_name -> openshell.policy.v1.ParameterMatcher
	34, // [34:34] is the sub-list for method output_type
	34, // [34:34] is the sub-list for method input_type
	34, // [34:34] is the sub-list for extension type_name
	34, // [34:34] is the sub-list for extension extendee
	0,  // [0:34] is the sub-list for field type_name
}

func init() { file_policy_proto_init() }
func file_policy_proto_init() {
	if File_policy_proto != nil {
		return
	}
	file_policy_proto_msgTypes[8].OneofWrappers = []any{}
	file_policy_proto_msgTypes[13].OneofWrappers = []any{
		(*Matcher_Glob)(nil),
		(*Matcher_Any)(nil),
	}
	file_policy_proto_msgTypes[15].OneofWrappers = []any{
		(*ParameterMatcher_Matcher)(nil),
		(*ParameterMatcher_Object)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_policy_proto_rawDesc), len(file_policy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_policy_proto_goTypes,
		DependencyIndexes: file_policy_proto_depIdxs,
		MessageInfos:      file_policy_proto_msgTypes,
	}.Build()
	File_policy_proto = out.File
	file_policy_proto_goTypes = nil
	file_policy_proto_depIdxs = nil
}
