# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

load("@crates//:defs.bzl", "aliases", "all_crate_deps")
load("@rules_rs//rs:rust_library.bzl", "rust_library")
load("@rules_rs//rs:rust_test.bzl", "rust_test")
load("@rules_rust//rust:defs.bzl", "rustfmt_test")

rust_library(
    name = "openshell-isolation",
    srcs = glob(["src/**/*.rs"]),
    aliases = aliases(),
    visibility = ["//visibility:public"],
    deps = all_crate_deps(normal = True),
)

rust_test(
    name = "openshell-isolation_test",
    crate = ":openshell-isolation",
    deps = all_crate_deps(normal_dev = True),
)

rustfmt_test(
    name = "rustfmt_test",
    targets = [
        ":openshell-isolation",
        ":openshell-isolation_test",
    ],
    visibility = ["//crates:__pkg__"],
)
