# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

FROM ghcr.io/nvidia/openshell-community/sandboxes/base:latest
ENV OPENSHELL_POLICY_POLL_INTERVAL_SECS=1
