// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v5.29.6
// source: datamodel.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "openshell.datamodel.v1";

/**
 * Kubernetes-style metadata shared by all top-level OpenShell domain objects.
 *
 * This structure provides consistent metadata (identity, labels, timestamps,
 * resource versioning) across Sandbox, Provider, SshSession, and other resources.
 */
export interface ObjectMeta {
  /** Stable object ID generated by the gateway. */
  id: string;
  /** Human-readable object name (unique per object type). */
  name: string;
  /** Milliseconds since Unix epoch when the object was created. */
  createdAtMs: number;
  /**
   * Key-value labels for filtering and organization.
   * Labels must follow Kubernetes conventions: alphanumeric + `-._/`, max 63 chars per segment.
   */
  labels: { [key: string]: string };
  /**
   * Optimistic concurrency control version.
   * Incremented by the gateway on each update. Clients can use this for compare-and-swap operations.
   */
  resourceVersion: number;
}

export interface ObjectMeta_LabelsEntry {
  key: string;
  value: string;
}

/** Provider model stored by OpenShell. */
export interface Provider {
  /** Kubernetes-style metadata (id, name, labels, timestamps, resource version). */
  metadata?:
    | ObjectMeta
    | undefined;
  /** Canonical provider type slug (for example: "claude", "gitlab"). */
  type: string;
  /** Secret values used for authentication. */
  credentials: { [key: string]: string };
  /** Non-secret provider configuration. */
  config: { [key: string]: string };
  /**
   * Expiration timestamps for credential values, keyed by credential/env var
   * name. A zero or missing value means the credential does not expire.
   */
  credentialExpiresAtMs: { [key: string]: number };
}

export interface Provider_CredentialsEntry {
  key: string;
  value: string;
}

export interface Provider_ConfigEntry {
  key: string;
  value: string;
}

export interface Provider_CredentialExpiresAtMsEntry {
  key: string;
  value: number;
}

function createBaseObjectMeta(): ObjectMeta {
  return { id: "", name: "", createdAtMs: 0, labels: {}, resourceVersion: 0 };
}

export const ObjectMeta: MessageFns<ObjectMeta> = {
  encode(message: ObjectMeta, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.createdAtMs !== 0) {
      writer.uint32(24).int64(message.createdAtMs);
    }
    globalThis.Object.entries(message.labels).forEach(([key, value]: [string, string]) => {
      ObjectMeta_LabelsEntry.encode({ key: key as any, value }, writer.uint32(34).fork()).join();
    });
    if (message.resourceVersion !== 0) {
      writer.uint32(40).uint64(message.resourceVersion);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ObjectMeta {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseObjectMeta();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.createdAtMs = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          const entry4 = ObjectMeta_LabelsEntry.decode(reader, reader.uint32());
          if (entry4.value !== undefined) {
            message.labels[entry4.key] = entry4.value;
          }
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.resourceVersion = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ObjectMeta {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      createdAtMs: isSet(object.createdAtMs)
        ? globalThis.Number(object.createdAtMs)
        : isSet(object.created_at_ms)
        ? globalThis.Number(object.created_at_ms)
        : 0,
      labels: isObject(object.labels)
        ? (globalThis.Object.entries(object.labels) as [string, any][]).reduce(
          (acc: { [key: string]: string }, [key, value]: [string, any]) => {
            acc[key] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : {},
      resourceVersion: isSet(object.resourceVersion)
        ? globalThis.Number(object.resourceVersion)
        : isSet(object.resource_version)
        ? globalThis.Number(object.resource_version)
        : 0,
    };
  },

  toJSON(message: ObjectMeta): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.createdAtMs !== 0) {
      obj.createdAtMs = Math.round(message.createdAtMs);
    }
    if (message.labels) {
      const entries = globalThis.Object.entries(message.labels) as [string, string][];
      if (entries.length > 0) {
        obj.labels = {};
        entries.forEach(([k, v]) => {
          obj.labels[k] = v;
        });
      }
    }
    if (message.resourceVersion !== 0) {
      obj.resourceVersion = Math.round(message.resourceVersion);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ObjectMeta>, I>>(base?: I): ObjectMeta {
    return ObjectMeta.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ObjectMeta>, I>>(object: I): ObjectMeta {
    const message = createBaseObjectMeta();
    message.id = object.id ?? "";
    message.name = object.name ?? "";
    message.createdAtMs = object.createdAtMs ?? 0;
    message.labels = (globalThis.Object.entries(object.labels ?? {}) as [string, string][]).reduce(
      (acc: { [key: string]: string }, [key, value]: [string, string]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    message.resourceVersion = object.resourceVersion ?? 0;
    return message;
  },
};

function createBaseObjectMeta_LabelsEntry(): ObjectMeta_LabelsEntry {
  return { key: "", value: "" };
}

export const ObjectMeta_LabelsEntry: MessageFns<ObjectMeta_LabelsEntry> = {
  encode(message: ObjectMeta_LabelsEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ObjectMeta_LabelsEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseObjectMeta_LabelsEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ObjectMeta_LabelsEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: ObjectMeta_LabelsEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ObjectMeta_LabelsEntry>, I>>(base?: I): ObjectMeta_LabelsEntry {
    return ObjectMeta_LabelsEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ObjectMeta_LabelsEntry>, I>>(object: I): ObjectMeta_LabelsEntry {
    const message = createBaseObjectMeta_LabelsEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseProvider(): Provider {
  return { metadata: undefined, type: "", credentials: {}, config: {}, credentialExpiresAtMs: {} };
}

export const Provider: MessageFns<Provider> = {
  encode(message: Provider, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.metadata !== undefined) {
      ObjectMeta.encode(message.metadata, writer.uint32(10).fork()).join();
    }
    if (message.type !== "") {
      writer.uint32(18).string(message.type);
    }
    globalThis.Object.entries(message.credentials).forEach(([key, value]: [string, string]) => {
      Provider_CredentialsEntry.encode({ key: key as any, value }, writer.uint32(26).fork()).join();
    });
    globalThis.Object.entries(message.config).forEach(([key, value]: [string, string]) => {
      Provider_ConfigEntry.encode({ key: key as any, value }, writer.uint32(34).fork()).join();
    });
    globalThis.Object.entries(message.credentialExpiresAtMs).forEach(([key, value]: [string, number]) => {
      Provider_CredentialExpiresAtMsEntry.encode({ key: key as any, value }, writer.uint32(42).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Provider {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseProvider();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.metadata = ObjectMeta.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.type = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          const entry3 = Provider_CredentialsEntry.decode(reader, reader.uint32());
          if (entry3.value !== undefined) {
            message.credentials[entry3.key] = entry3.value;
          }
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          const entry4 = Provider_ConfigEntry.decode(reader, reader.uint32());
          if (entry4.value !== undefined) {
            message.config[entry4.key] = entry4.value;
          }
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          const entry5 = Provider_CredentialExpiresAtMsEntry.decode(reader, reader.uint32());
          if (entry5.value !== undefined) {
            message.credentialExpiresAtMs[entry5.key] = entry5.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Provider {
    return {
      metadata: isSet(object.metadata) ? ObjectMeta.fromJSON(object.metadata) : undefined,
      type: isSet(object.type) ? globalThis.String(object.type) : "",
      credentials: isObject(object.credentials)
        ? (globalThis.Object.entries(object.credentials) as [string, any][]).reduce(
          (acc: { [key: string]: string }, [key, value]: [string, any]) => {
            acc[key] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : {},
      config: isObject(object.config)
        ? (globalThis.Object.entries(object.config) as [string, any][]).reduce(
          (acc: { [key: string]: string }, [key, value]: [string, any]) => {
            acc[key] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : {},
      credentialExpiresAtMs: isObject(object.credentialExpiresAtMs)
        ? (globalThis.Object.entries(object.credentialExpiresAtMs) as [string, any][]).reduce(
          (acc: { [key: string]: number }, [key, value]: [string, any]) => {
            acc[key] = globalThis.Number(value);
            return acc;
          },
          {},
        )
        : isObject(object.credential_expires_at_ms)
        ? (globalThis.Object.entries(object.credential_expires_at_ms) as [string, any][]).reduce(
          (acc: { [key: string]: number }, [key, value]: [string, any]) => {
            acc[key] = globalThis.Number(value);
            return acc;
          },
          {},
        )
        : {},
    };
  },

  toJSON(message: Provider): unknown {
    const obj: any = {};
    if (message.metadata !== undefined) {
      obj.metadata = ObjectMeta.toJSON(message.metadata);
    }
    if (message.type !== "") {
      obj.type = message.type;
    }
    if (message.credentials) {
      const entries = globalThis.Object.entries(message.credentials) as [string, string][];
      if (entries.length > 0) {
        obj.credentials = {};
        entries.forEach(([k, v]) => {
          obj.credentials[k] = v;
        });
      }
    }
    if (message.config) {
      const entries = globalThis.Object.entries(message.config) as [string, string][];
      if (entries.length > 0) {
        obj.config = {};
        entries.forEach(([k, v]) => {
          obj.config[k] = v;
        });
      }
    }
    if (message.credentialExpiresAtMs) {
      const entries = globalThis.Object.entries(message.credentialExpiresAtMs) as [string, number][];
      if (entries.length > 0) {
        obj.credentialExpiresAtMs = {};
        entries.forEach(([k, v]) => {
          obj.credentialExpiresAtMs[k] = Math.round(v);
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Provider>, I>>(base?: I): Provider {
    return Provider.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Provider>, I>>(object: I): Provider {
    const message = createBaseProvider();
    message.metadata = (object.metadata !== undefined && object.metadata !== null)
      ? ObjectMeta.fromPartial(object.metadata)
      : undefined;
    message.type = object.type ?? "";
    message.credentials = (globalThis.Object.entries(object.credentials ?? {}) as [string, string][]).reduce(
      (acc: { [key: string]: string }, [key, value]: [string, string]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    message.config = (globalThis.Object.entries(object.config ?? {}) as [string, string][]).reduce(
      (acc: { [key: string]: string }, [key, value]: [string, string]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    message.credentialExpiresAtMs =
      (globalThis.Object.entries(object.credentialExpiresAtMs ?? {}) as [string, number][]).reduce(
        (acc: { [key: string]: number }, [key, value]: [string, number]) => {
          if (value !== undefined) {
            acc[key] = globalThis.Number(value);
          }
          return acc;
        },
        {},
      );
    return message;
  },
};

function createBaseProvider_CredentialsEntry(): Provider_CredentialsEntry {
  return { key: "", value: "" };
}

export const Provider_CredentialsEntry: MessageFns<Provider_CredentialsEntry> = {
  encode(message: Provider_CredentialsEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Provider_CredentialsEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseProvider_CredentialsEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Provider_CredentialsEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: Provider_CredentialsEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Provider_CredentialsEntry>, I>>(base?: I): Provider_CredentialsEntry {
    return Provider_CredentialsEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Provider_CredentialsEntry>, I>>(object: I): Provider_CredentialsEntry {
    const message = createBaseProvider_CredentialsEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseProvider_ConfigEntry(): Provider_ConfigEntry {
  return { key: "", value: "" };
}

export const Provider_ConfigEntry: MessageFns<Provider_ConfigEntry> = {
  encode(message: Provider_ConfigEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Provider_ConfigEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseProvider_ConfigEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Provider_ConfigEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: Provider_ConfigEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Provider_ConfigEntry>, I>>(base?: I): Provider_ConfigEntry {
    return Provider_ConfigEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Provider_ConfigEntry>, I>>(object: I): Provider_ConfigEntry {
    const message = createBaseProvider_ConfigEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseProvider_CredentialExpiresAtMsEntry(): Provider_CredentialExpiresAtMsEntry {
  return { key: "", value: 0 };
}

export const Provider_CredentialExpiresAtMsEntry: MessageFns<Provider_CredentialExpiresAtMsEntry> = {
  encode(message: Provider_CredentialExpiresAtMsEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== 0) {
      writer.uint32(16).int64(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Provider_CredentialExpiresAtMsEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseProvider_CredentialExpiresAtMsEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.value = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Provider_CredentialExpiresAtMsEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.Number(object.value) : 0,
    };
  },

  toJSON(message: Provider_CredentialExpiresAtMsEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== 0) {
      obj.value = Math.round(message.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Provider_CredentialExpiresAtMsEntry>, I>>(
    base?: I,
  ): Provider_CredentialExpiresAtMsEntry {
    return Provider_CredentialExpiresAtMsEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Provider_CredentialExpiresAtMsEntry>, I>>(
    object: I,
  ): Provider_CredentialExpiresAtMsEntry {
    const message = createBaseProvider_CredentialExpiresAtMsEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string } ? { [K in keyof Omit<T, "$case">]?: DeepPartial<T[K]> } & { $case: T["$case"] }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
