// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v5.29.6
// source: inference.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import { ObjectMeta } from "./datamodel";

export const protobufPackage = "openshell.inference.v1";

/**
 * Persisted cluster inference configuration.
 *
 * Only `provider_name` and `model_id` are stored; endpoint, protocols,
 * credentials, and auth style are resolved from the provider at bundle time.
 */
export interface ClusterInferenceConfig {
  /** Provider record name backing this route. */
  providerName: string;
  /** Model identifier to force on generation calls. */
  modelId: string;
  /** Per-route request timeout in seconds. 0 means use default (60s). */
  timeoutSecs: number;
}

/** Storage envelope for the managed cluster inference route. */
export interface InferenceRoute {
  metadata?: ObjectMeta | undefined;
  config?:
    | ClusterInferenceConfig
    | undefined;
  /** Monotonic version incremented on every update. */
  version: number;
}

export interface SetClusterInferenceRequest {
  /** Provider record name to use for credentials + endpoint mapping. */
  providerName: string;
  /** Model identifier to force on generation calls. */
  modelId: string;
  /**
   * Route name to target. Empty string defaults to "inference.local" (user-facing).
   * Use "sandbox-system" for the sandbox system-level inference route.
   */
  routeName: string;
  /** Verify the resolved upstream endpoint synchronously before persistence. */
  verify: boolean;
  /** Skip synchronous endpoint validation before persistence. */
  noVerify: boolean;
  /** Per-route request timeout in seconds. 0 means use default (60s). */
  timeoutSecs: number;
}

export interface ValidatedEndpoint {
  url: string;
  protocol: string;
}

export interface SetClusterInferenceResponse {
  providerName: string;
  modelId: string;
  version: number;
  /** Route name that was configured. */
  routeName: string;
  /** Whether endpoint verification ran as part of this request. */
  validationPerformed: boolean;
  /** The concrete endpoints that were probed during validation, when available. */
  validatedEndpoints: ValidatedEndpoint[];
  /** Per-route request timeout in seconds that was persisted. */
  timeoutSecs: number;
}

export interface GetClusterInferenceRequest {
  /**
   * Route name to query. Empty string defaults to "inference.local" (user-facing).
   * Use "sandbox-system" for the sandbox system-level inference route.
   */
  routeName: string;
}

export interface GetClusterInferenceResponse {
  providerName: string;
  modelId: string;
  version: number;
  /** Route name that was queried. */
  routeName: string;
  /** Per-route request timeout in seconds. 0 means default (60s). */
  timeoutSecs: number;
}

export interface GetInferenceBundleRequest {
}

/** A single resolved route ready for sandbox-local execution. */
export interface ResolvedRoute {
  name: string;
  baseUrl: string;
  protocols: string[];
  apiKey: string;
  modelId: string;
  providerType: string;
  /** Per-route request timeout in seconds. 0 means use default (60s). */
  timeoutSecs: number;
}

export interface GetInferenceBundleResponse {
  routes: ResolvedRoute[];
  /** Opaque revision tag for cache freshness checks. */
  revision: string;
  /** Timestamp (epoch ms) when this bundle was generated. */
  generatedAtMs: number;
}

function createBaseClusterInferenceConfig(): ClusterInferenceConfig {
  return { providerName: "", modelId: "", timeoutSecs: 0 };
}

export const ClusterInferenceConfig: MessageFns<ClusterInferenceConfig> = {
  encode(message: ClusterInferenceConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.providerName !== "") {
      writer.uint32(10).string(message.providerName);
    }
    if (message.modelId !== "") {
      writer.uint32(18).string(message.modelId);
    }
    if (message.timeoutSecs !== 0) {
      writer.uint32(24).uint64(message.timeoutSecs);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ClusterInferenceConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseClusterInferenceConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.providerName = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.modelId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.timeoutSecs = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ClusterInferenceConfig {
    return {
      providerName: isSet(object.providerName)
        ? globalThis.String(object.providerName)
        : isSet(object.provider_name)
        ? globalThis.String(object.provider_name)
        : "",
      modelId: isSet(object.modelId)
        ? globalThis.String(object.modelId)
        : isSet(object.model_id)
        ? globalThis.String(object.model_id)
        : "",
      timeoutSecs: isSet(object.timeoutSecs)
        ? globalThis.Number(object.timeoutSecs)
        : isSet(object.timeout_secs)
        ? globalThis.Number(object.timeout_secs)
        : 0,
    };
  },

  toJSON(message: ClusterInferenceConfig): unknown {
    const obj: any = {};
    if (message.providerName !== "") {
      obj.providerName = message.providerName;
    }
    if (message.modelId !== "") {
      obj.modelId = message.modelId;
    }
    if (message.timeoutSecs !== 0) {
      obj.timeoutSecs = Math.round(message.timeoutSecs);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ClusterInferenceConfig>, I>>(base?: I): ClusterInferenceConfig {
    return ClusterInferenceConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ClusterInferenceConfig>, I>>(object: I): ClusterInferenceConfig {
    const message = createBaseClusterInferenceConfig();
    message.providerName = object.providerName ?? "";
    message.modelId = object.modelId ?? "";
    message.timeoutSecs = object.timeoutSecs ?? 0;
    return message;
  },
};

function createBaseInferenceRoute(): InferenceRoute {
  return { metadata: undefined, config: undefined, version: 0 };
}

export const InferenceRoute: MessageFns<InferenceRoute> = {
  encode(message: InferenceRoute, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.metadata !== undefined) {
      ObjectMeta.encode(message.metadata, writer.uint32(10).fork()).join();
    }
    if (message.config !== undefined) {
      ClusterInferenceConfig.encode(message.config, writer.uint32(18).fork()).join();
    }
    if (message.version !== 0) {
      writer.uint32(24).uint64(message.version);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): InferenceRoute {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseInferenceRoute();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.metadata = ObjectMeta.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.config = ClusterInferenceConfig.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.version = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): InferenceRoute {
    return {
      metadata: isSet(object.metadata) ? ObjectMeta.fromJSON(object.metadata) : undefined,
      config: isSet(object.config) ? ClusterInferenceConfig.fromJSON(object.config) : undefined,
      version: isSet(object.version) ? globalThis.Number(object.version) : 0,
    };
  },

  toJSON(message: InferenceRoute): unknown {
    const obj: any = {};
    if (message.metadata !== undefined) {
      obj.metadata = ObjectMeta.toJSON(message.metadata);
    }
    if (message.config !== undefined) {
      obj.config = ClusterInferenceConfig.toJSON(message.config);
    }
    if (message.version !== 0) {
      obj.version = Math.round(message.version);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<InferenceRoute>, I>>(base?: I): InferenceRoute {
    return InferenceRoute.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<InferenceRoute>, I>>(object: I): InferenceRoute {
    const message = createBaseInferenceRoute();
    message.metadata = (object.metadata !== undefined && object.metadata !== null)
      ? ObjectMeta.fromPartial(object.metadata)
      : undefined;
    message.config = (object.config !== undefined && object.config !== null)
      ? ClusterInferenceConfig.fromPartial(object.config)
      : undefined;
    message.version = object.version ?? 0;
    return message;
  },
};

function createBaseSetClusterInferenceRequest(): SetClusterInferenceRequest {
  return { providerName: "", modelId: "", routeName: "", verify: false, noVerify: false, timeoutSecs: 0 };
}

export const SetClusterInferenceRequest: MessageFns<SetClusterInferenceRequest> = {
  encode(message: SetClusterInferenceRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.providerName !== "") {
      writer.uint32(10).string(message.providerName);
    }
    if (message.modelId !== "") {
      writer.uint32(18).string(message.modelId);
    }
    if (message.routeName !== "") {
      writer.uint32(26).string(message.routeName);
    }
    if (message.verify !== false) {
      writer.uint32(32).bool(message.verify);
    }
    if (message.noVerify !== false) {
      writer.uint32(40).bool(message.noVerify);
    }
    if (message.timeoutSecs !== 0) {
      writer.uint32(48).uint64(message.timeoutSecs);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SetClusterInferenceRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetClusterInferenceRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.providerName = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.modelId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.routeName = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.verify = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.noVerify = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.timeoutSecs = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SetClusterInferenceRequest {
    return {
      providerName: isSet(object.providerName)
        ? globalThis.String(object.providerName)
        : isSet(object.provider_name)
        ? globalThis.String(object.provider_name)
        : "",
      modelId: isSet(object.modelId)
        ? globalThis.String(object.modelId)
        : isSet(object.model_id)
        ? globalThis.String(object.model_id)
        : "",
      routeName: isSet(object.routeName)
        ? globalThis.String(object.routeName)
        : isSet(object.route_name)
        ? globalThis.String(object.route_name)
        : "",
      verify: isSet(object.verify) ? globalThis.Boolean(object.verify) : false,
      noVerify: isSet(object.noVerify)
        ? globalThis.Boolean(object.noVerify)
        : isSet(object.no_verify)
        ? globalThis.Boolean(object.no_verify)
        : false,
      timeoutSecs: isSet(object.timeoutSecs)
        ? globalThis.Number(object.timeoutSecs)
        : isSet(object.timeout_secs)
        ? globalThis.Number(object.timeout_secs)
        : 0,
    };
  },

  toJSON(message: SetClusterInferenceRequest): unknown {
    const obj: any = {};
    if (message.providerName !== "") {
      obj.providerName = message.providerName;
    }
    if (message.modelId !== "") {
      obj.modelId = message.modelId;
    }
    if (message.routeName !== "") {
      obj.routeName = message.routeName;
    }
    if (message.verify !== false) {
      obj.verify = message.verify;
    }
    if (message.noVerify !== false) {
      obj.noVerify = message.noVerify;
    }
    if (message.timeoutSecs !== 0) {
      obj.timeoutSecs = Math.round(message.timeoutSecs);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SetClusterInferenceRequest>, I>>(base?: I): SetClusterInferenceRequest {
    return SetClusterInferenceRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SetClusterInferenceRequest>, I>>(object: I): SetClusterInferenceRequest {
    const message = createBaseSetClusterInferenceRequest();
    message.providerName = object.providerName ?? "";
    message.modelId = object.modelId ?? "";
    message.routeName = object.routeName ?? "";
    message.verify = object.verify ?? false;
    message.noVerify = object.noVerify ?? false;
    message.timeoutSecs = object.timeoutSecs ?? 0;
    return message;
  },
};

function createBaseValidatedEndpoint(): ValidatedEndpoint {
  return { url: "", protocol: "" };
}

export const ValidatedEndpoint: MessageFns<ValidatedEndpoint> = {
  encode(message: ValidatedEndpoint, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.url !== "") {
      writer.uint32(10).string(message.url);
    }
    if (message.protocol !== "") {
      writer.uint32(18).string(message.protocol);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ValidatedEndpoint {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseValidatedEndpoint();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.url = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.protocol = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ValidatedEndpoint {
    return {
      url: isSet(object.url) ? globalThis.String(object.url) : "",
      protocol: isSet(object.protocol) ? globalThis.String(object.protocol) : "",
    };
  },

  toJSON(message: ValidatedEndpoint): unknown {
    const obj: any = {};
    if (message.url !== "") {
      obj.url = message.url;
    }
    if (message.protocol !== "") {
      obj.protocol = message.protocol;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ValidatedEndpoint>, I>>(base?: I): ValidatedEndpoint {
    return ValidatedEndpoint.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ValidatedEndpoint>, I>>(object: I): ValidatedEndpoint {
    const message = createBaseValidatedEndpoint();
    message.url = object.url ?? "";
    message.protocol = object.protocol ?? "";
    return message;
  },
};

function createBaseSetClusterInferenceResponse(): SetClusterInferenceResponse {
  return {
    providerName: "",
    modelId: "",
    version: 0,
    routeName: "",
    validationPerformed: false,
    validatedEndpoints: [],
    timeoutSecs: 0,
  };
}

export const SetClusterInferenceResponse: MessageFns<SetClusterInferenceResponse> = {
  encode(message: SetClusterInferenceResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.providerName !== "") {
      writer.uint32(10).string(message.providerName);
    }
    if (message.modelId !== "") {
      writer.uint32(18).string(message.modelId);
    }
    if (message.version !== 0) {
      writer.uint32(24).uint64(message.version);
    }
    if (message.routeName !== "") {
      writer.uint32(34).string(message.routeName);
    }
    if (message.validationPerformed !== false) {
      writer.uint32(40).bool(message.validationPerformed);
    }
    for (const v of message.validatedEndpoints) {
      ValidatedEndpoint.encode(v!, writer.uint32(50).fork()).join();
    }
    if (message.timeoutSecs !== 0) {
      writer.uint32(56).uint64(message.timeoutSecs);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SetClusterInferenceResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetClusterInferenceResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.providerName = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.modelId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.version = longToNumber(reader.uint64());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.routeName = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.validationPerformed = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.validatedEndpoints.push(ValidatedEndpoint.decode(reader, reader.uint32()));
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.timeoutSecs = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SetClusterInferenceResponse {
    return {
      providerName: isSet(object.providerName)
        ? globalThis.String(object.providerName)
        : isSet(object.provider_name)
        ? globalThis.String(object.provider_name)
        : "",
      modelId: isSet(object.modelId)
        ? globalThis.String(object.modelId)
        : isSet(object.model_id)
        ? globalThis.String(object.model_id)
        : "",
      version: isSet(object.version) ? globalThis.Number(object.version) : 0,
      routeName: isSet(object.routeName)
        ? globalThis.String(object.routeName)
        : isSet(object.route_name)
        ? globalThis.String(object.route_name)
        : "",
      validationPerformed: isSet(object.validationPerformed)
        ? globalThis.Boolean(object.validationPerformed)
        : isSet(object.validation_performed)
        ? globalThis.Boolean(object.validation_performed)
        : false,
      validatedEndpoints: globalThis.Array.isArray(object?.validatedEndpoints)
        ? object.validatedEndpoints.map((e: any) => ValidatedEndpoint.fromJSON(e))
        : globalThis.Array.isArray(object?.validated_endpoints)
        ? object.validated_endpoints.map((e: any) => ValidatedEndpoint.fromJSON(e))
        : [],
      timeoutSecs: isSet(object.timeoutSecs)
        ? globalThis.Number(object.timeoutSecs)
        : isSet(object.timeout_secs)
        ? globalThis.Number(object.timeout_secs)
        : 0,
    };
  },

  toJSON(message: SetClusterInferenceResponse): unknown {
    const obj: any = {};
    if (message.providerName !== "") {
      obj.providerName = message.providerName;
    }
    if (message.modelId !== "") {
      obj.modelId = message.modelId;
    }
    if (message.version !== 0) {
      obj.version = Math.round(message.version);
    }
    if (message.routeName !== "") {
      obj.routeName = message.routeName;
    }
    if (message.validationPerformed !== false) {
      obj.validationPerformed = message.validationPerformed;
    }
    if (message.validatedEndpoints?.length) {
      obj.validatedEndpoints = message.validatedEndpoints.map((e) => ValidatedEndpoint.toJSON(e));
    }
    if (message.timeoutSecs !== 0) {
      obj.timeoutSecs = Math.round(message.timeoutSecs);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SetClusterInferenceResponse>, I>>(base?: I): SetClusterInferenceResponse {
    return SetClusterInferenceResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SetClusterInferenceResponse>, I>>(object: I): SetClusterInferenceResponse {
    const message = createBaseSetClusterInferenceResponse();
    message.providerName = object.providerName ?? "";
    message.modelId = object.modelId ?? "";
    message.version = object.version ?? 0;
    message.routeName = object.routeName ?? "";
    message.validationPerformed = object.validationPerformed ?? false;
    message.validatedEndpoints = object.validatedEndpoints?.map((e) => ValidatedEndpoint.fromPartial(e)) || [];
    message.timeoutSecs = object.timeoutSecs ?? 0;
    return message;
  },
};

function createBaseGetClusterInferenceRequest(): GetClusterInferenceRequest {
  return { routeName: "" };
}

export const GetClusterInferenceRequest: MessageFns<GetClusterInferenceRequest> = {
  encode(message: GetClusterInferenceRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.routeName !== "") {
      writer.uint32(10).string(message.routeName);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetClusterInferenceRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetClusterInferenceRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.routeName = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetClusterInferenceRequest {
    return {
      routeName: isSet(object.routeName)
        ? globalThis.String(object.routeName)
        : isSet(object.route_name)
        ? globalThis.String(object.route_name)
        : "",
    };
  },

  toJSON(message: GetClusterInferenceRequest): unknown {
    const obj: any = {};
    if (message.routeName !== "") {
      obj.routeName = message.routeName;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetClusterInferenceRequest>, I>>(base?: I): GetClusterInferenceRequest {
    return GetClusterInferenceRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetClusterInferenceRequest>, I>>(object: I): GetClusterInferenceRequest {
    const message = createBaseGetClusterInferenceRequest();
    message.routeName = object.routeName ?? "";
    return message;
  },
};

function createBaseGetClusterInferenceResponse(): GetClusterInferenceResponse {
  return { providerName: "", modelId: "", version: 0, routeName: "", timeoutSecs: 0 };
}

export const GetClusterInferenceResponse: MessageFns<GetClusterInferenceResponse> = {
  encode(message: GetClusterInferenceResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.providerName !== "") {
      writer.uint32(10).string(message.providerName);
    }
    if (message.modelId !== "") {
      writer.uint32(18).string(message.modelId);
    }
    if (message.version !== 0) {
      writer.uint32(24).uint64(message.version);
    }
    if (message.routeName !== "") {
      writer.uint32(34).string(message.routeName);
    }
    if (message.timeoutSecs !== 0) {
      writer.uint32(40).uint64(message.timeoutSecs);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetClusterInferenceResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetClusterInferenceResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.providerName = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.modelId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.version = longToNumber(reader.uint64());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.routeName = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.timeoutSecs = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetClusterInferenceResponse {
    return {
      providerName: isSet(object.providerName)
        ? globalThis.String(object.providerName)
        : isSet(object.provider_name)
        ? globalThis.String(object.provider_name)
        : "",
      modelId: isSet(object.modelId)
        ? globalThis.String(object.modelId)
        : isSet(object.model_id)
        ? globalThis.String(object.model_id)
        : "",
      version: isSet(object.version) ? globalThis.Number(object.version) : 0,
      routeName: isSet(object.routeName)
        ? globalThis.String(object.routeName)
        : isSet(object.route_name)
        ? globalThis.String(object.route_name)
        : "",
      timeoutSecs: isSet(object.timeoutSecs)
        ? globalThis.Number(object.timeoutSecs)
        : isSet(object.timeout_secs)
        ? globalThis.Number(object.timeout_secs)
        : 0,
    };
  },

  toJSON(message: GetClusterInferenceResponse): unknown {
    const obj: any = {};
    if (message.providerName !== "") {
      obj.providerName = message.providerName;
    }
    if (message.modelId !== "") {
      obj.modelId = message.modelId;
    }
    if (message.version !== 0) {
      obj.version = Math.round(message.version);
    }
    if (message.routeName !== "") {
      obj.routeName = message.routeName;
    }
    if (message.timeoutSecs !== 0) {
      obj.timeoutSecs = Math.round(message.timeoutSecs);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetClusterInferenceResponse>, I>>(base?: I): GetClusterInferenceResponse {
    return GetClusterInferenceResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetClusterInferenceResponse>, I>>(object: I): GetClusterInferenceResponse {
    const message = createBaseGetClusterInferenceResponse();
    message.providerName = object.providerName ?? "";
    message.modelId = object.modelId ?? "";
    message.version = object.version ?? 0;
    message.routeName = object.routeName ?? "";
    message.timeoutSecs = object.timeoutSecs ?? 0;
    return message;
  },
};

function createBaseGetInferenceBundleRequest(): GetInferenceBundleRequest {
  return {};
}

export const GetInferenceBundleRequest: MessageFns<GetInferenceBundleRequest> = {
  encode(_: GetInferenceBundleRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetInferenceBundleRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetInferenceBundleRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): GetInferenceBundleRequest {
    return {};
  },

  toJSON(_: GetInferenceBundleRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<GetInferenceBundleRequest>, I>>(base?: I): GetInferenceBundleRequest {
    return GetInferenceBundleRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetInferenceBundleRequest>, I>>(_: I): GetInferenceBundleRequest {
    const message = createBaseGetInferenceBundleRequest();
    return message;
  },
};

function createBaseResolvedRoute(): ResolvedRoute {
  return { name: "", baseUrl: "", protocols: [], apiKey: "", modelId: "", providerType: "", timeoutSecs: 0 };
}

export const ResolvedRoute: MessageFns<ResolvedRoute> = {
  encode(message: ResolvedRoute, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.baseUrl !== "") {
      writer.uint32(18).string(message.baseUrl);
    }
    for (const v of message.protocols) {
      writer.uint32(26).string(v!);
    }
    if (message.apiKey !== "") {
      writer.uint32(34).string(message.apiKey);
    }
    if (message.modelId !== "") {
      writer.uint32(42).string(message.modelId);
    }
    if (message.providerType !== "") {
      writer.uint32(50).string(message.providerType);
    }
    if (message.timeoutSecs !== 0) {
      writer.uint32(56).uint64(message.timeoutSecs);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ResolvedRoute {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResolvedRoute();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.baseUrl = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.protocols.push(reader.string());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.apiKey = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.modelId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.providerType = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.timeoutSecs = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ResolvedRoute {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      baseUrl: isSet(object.baseUrl)
        ? globalThis.String(object.baseUrl)
        : isSet(object.base_url)
        ? globalThis.String(object.base_url)
        : "",
      protocols: globalThis.Array.isArray(object?.protocols)
        ? object.protocols.map((e: any) => globalThis.String(e))
        : [],
      apiKey: isSet(object.apiKey)
        ? globalThis.String(object.apiKey)
        : isSet(object.api_key)
        ? globalThis.String(object.api_key)
        : "",
      modelId: isSet(object.modelId)
        ? globalThis.String(object.modelId)
        : isSet(object.model_id)
        ? globalThis.String(object.model_id)
        : "",
      providerType: isSet(object.providerType)
        ? globalThis.String(object.providerType)
        : isSet(object.provider_type)
        ? globalThis.String(object.provider_type)
        : "",
      timeoutSecs: isSet(object.timeoutSecs)
        ? globalThis.Number(object.timeoutSecs)
        : isSet(object.timeout_secs)
        ? globalThis.Number(object.timeout_secs)
        : 0,
    };
  },

  toJSON(message: ResolvedRoute): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.baseUrl !== "") {
      obj.baseUrl = message.baseUrl;
    }
    if (message.protocols?.length) {
      obj.protocols = message.protocols;
    }
    if (message.apiKey !== "") {
      obj.apiKey = message.apiKey;
    }
    if (message.modelId !== "") {
      obj.modelId = message.modelId;
    }
    if (message.providerType !== "") {
      obj.providerType = message.providerType;
    }
    if (message.timeoutSecs !== 0) {
      obj.timeoutSecs = Math.round(message.timeoutSecs);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ResolvedRoute>, I>>(base?: I): ResolvedRoute {
    return ResolvedRoute.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ResolvedRoute>, I>>(object: I): ResolvedRoute {
    const message = createBaseResolvedRoute();
    message.name = object.name ?? "";
    message.baseUrl = object.baseUrl ?? "";
    message.protocols = object.protocols?.map((e) => e) || [];
    message.apiKey = object.apiKey ?? "";
    message.modelId = object.modelId ?? "";
    message.providerType = object.providerType ?? "";
    message.timeoutSecs = object.timeoutSecs ?? 0;
    return message;
  },
};

function createBaseGetInferenceBundleResponse(): GetInferenceBundleResponse {
  return { routes: [], revision: "", generatedAtMs: 0 };
}

export const GetInferenceBundleResponse: MessageFns<GetInferenceBundleResponse> = {
  encode(message: GetInferenceBundleResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.routes) {
      ResolvedRoute.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.revision !== "") {
      writer.uint32(18).string(message.revision);
    }
    if (message.generatedAtMs !== 0) {
      writer.uint32(24).int64(message.generatedAtMs);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetInferenceBundleResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetInferenceBundleResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.routes.push(ResolvedRoute.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.revision = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.generatedAtMs = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetInferenceBundleResponse {
    return {
      routes: globalThis.Array.isArray(object?.routes) ? object.routes.map((e: any) => ResolvedRoute.fromJSON(e)) : [],
      revision: isSet(object.revision) ? globalThis.String(object.revision) : "",
      generatedAtMs: isSet(object.generatedAtMs)
        ? globalThis.Number(object.generatedAtMs)
        : isSet(object.generated_at_ms)
        ? globalThis.Number(object.generated_at_ms)
        : 0,
    };
  },

  toJSON(message: GetInferenceBundleResponse): unknown {
    const obj: any = {};
    if (message.routes?.length) {
      obj.routes = message.routes.map((e) => ResolvedRoute.toJSON(e));
    }
    if (message.revision !== "") {
      obj.revision = message.revision;
    }
    if (message.generatedAtMs !== 0) {
      obj.generatedAtMs = Math.round(message.generatedAtMs);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetInferenceBundleResponse>, I>>(base?: I): GetInferenceBundleResponse {
    return GetInferenceBundleResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetInferenceBundleResponse>, I>>(object: I): GetInferenceBundleResponse {
    const message = createBaseGetInferenceBundleResponse();
    message.routes = object.routes?.map((e) => ResolvedRoute.fromPartial(e)) || [];
    message.revision = object.revision ?? "";
    message.generatedAtMs = object.generatedAtMs ?? 0;
    return message;
  },
};

/** Inference service provides cluster inference configuration and bundle delivery. */
export type InferenceService = typeof InferenceService;
export const InferenceService = {
  /** Return the resolved inference route bundle for sandbox-local execution. */
  getInferenceBundle: {
    path: "/openshell.inference.v1.Inference/GetInferenceBundle" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetInferenceBundleRequest): Buffer =>
      Buffer.from(GetInferenceBundleRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetInferenceBundleRequest => GetInferenceBundleRequest.decode(value),
    responseSerialize: (value: GetInferenceBundleResponse): Buffer =>
      Buffer.from(GetInferenceBundleResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetInferenceBundleResponse => GetInferenceBundleResponse.decode(value),
  },
  /**
   * Set cluster-level inference configuration.
   *
   * This controls how requests sent to `inference.local` are routed.
   */
  setClusterInference: {
    path: "/openshell.inference.v1.Inference/SetClusterInference" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: SetClusterInferenceRequest): Buffer =>
      Buffer.from(SetClusterInferenceRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): SetClusterInferenceRequest => SetClusterInferenceRequest.decode(value),
    responseSerialize: (value: SetClusterInferenceResponse): Buffer =>
      Buffer.from(SetClusterInferenceResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): SetClusterInferenceResponse => SetClusterInferenceResponse.decode(value),
  },
  /** Get cluster-level inference configuration. */
  getClusterInference: {
    path: "/openshell.inference.v1.Inference/GetClusterInference" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetClusterInferenceRequest): Buffer =>
      Buffer.from(GetClusterInferenceRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetClusterInferenceRequest => GetClusterInferenceRequest.decode(value),
    responseSerialize: (value: GetClusterInferenceResponse): Buffer =>
      Buffer.from(GetClusterInferenceResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetClusterInferenceResponse => GetClusterInferenceResponse.decode(value),
  },
} as const;

export interface InferenceServer extends UntypedServiceImplementation {
  /** Return the resolved inference route bundle for sandbox-local execution. */
  getInferenceBundle: handleUnaryCall<GetInferenceBundleRequest, GetInferenceBundleResponse>;
  /**
   * Set cluster-level inference configuration.
   *
   * This controls how requests sent to `inference.local` are routed.
   */
  setClusterInference: handleUnaryCall<SetClusterInferenceRequest, SetClusterInferenceResponse>;
  /** Get cluster-level inference configuration. */
  getClusterInference: handleUnaryCall<GetClusterInferenceRequest, GetClusterInferenceResponse>;
}

export interface InferenceClient extends Client {
  /** Return the resolved inference route bundle for sandbox-local execution. */
  getInferenceBundle(
    request: GetInferenceBundleRequest,
    callback: (error: ServiceError | null, response: GetInferenceBundleResponse) => void,
  ): ClientUnaryCall;
  getInferenceBundle(
    request: GetInferenceBundleRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetInferenceBundleResponse) => void,
  ): ClientUnaryCall;
  getInferenceBundle(
    request: GetInferenceBundleRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetInferenceBundleResponse) => void,
  ): ClientUnaryCall;
  /**
   * Set cluster-level inference configuration.
   *
   * This controls how requests sent to `inference.local` are routed.
   */
  setClusterInference(
    request: SetClusterInferenceRequest,
    callback: (error: ServiceError | null, response: SetClusterInferenceResponse) => void,
  ): ClientUnaryCall;
  setClusterInference(
    request: SetClusterInferenceRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: SetClusterInferenceResponse) => void,
  ): ClientUnaryCall;
  setClusterInference(
    request: SetClusterInferenceRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: SetClusterInferenceResponse) => void,
  ): ClientUnaryCall;
  /** Get cluster-level inference configuration. */
  getClusterInference(
    request: GetClusterInferenceRequest,
    callback: (error: ServiceError | null, response: GetClusterInferenceResponse) => void,
  ): ClientUnaryCall;
  getClusterInference(
    request: GetClusterInferenceRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetClusterInferenceResponse) => void,
  ): ClientUnaryCall;
  getClusterInference(
    request: GetClusterInferenceRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetClusterInferenceResponse) => void,
  ): ClientUnaryCall;
}

export const InferenceClient = makeGenericClientConstructor(
  InferenceService,
  "openshell.inference.v1.Inference",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): InferenceClient;
  service: typeof InferenceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string } ? { [K in keyof Omit<T, "$case">]?: DeepPartial<T[K]> } & { $case: T["$case"] }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
