# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

version: 1
network_policies:
  default-egress:
    endpoints:
      - host: example.com
        port: 443
        protocol: https
      - host: google.com
        port: 443
        protocol: https
      - host: nvidia.com
        port: 443
        protocol: https
    binaries: []
