load(
    ":test_guest.bzl",
    "test_guest_host_tools",
)

exports_files([
    "build-image.sh",
    "host-tools.BUILD.bazel",
    "host-tools.nix",
    "image-seal.sh",
    "nixpkgs.nix",
    "run.sh",
    "test-guest.MODULE.bazel",
])

toolchain_type(name = "host_tools_toolchain_type")

test_guest_host_tools(
    name = "nix_host_tools",
    all_files = "@test_guest_host_tools//:all",
    ansible_version = "@test_guest_host_tools//:ansible_version",
    bash = "@test_guest_host_tools//:bash",
    jq = "@test_guest_host_tools//:jq",
    qemu_img = "@test_guest_host_tools//:qemu_img",
    qemu_version = "@test_guest_host_tools//:qemu_version",
    runner = "@test_guest_host_tools//:runner",
    sha256sum = "@test_guest_host_tools//:sha256sum",
)

toolchain(
    name = "nix_host_tools_toolchain",
    toolchain = ":nix_host_tools",
    toolchain_type = ":host_tools_toolchain_type",
    use_target_platform_constraints = True,
)
