name: Debian Package

on:
  workflow_call:
    inputs:
      deb-version:
        required: true
        type: string
      checkout-ref:
        required: true
        type: string

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  build-deb-linux:
    strategy:
      matrix:
        include:
          - arch: amd64
            runner: linux-amd64-cpu8
            cli_target: x86_64-unknown-linux-musl
            gnu_target: x86_64-unknown-linux-gnu
          - arch: arm64
            runner: linux-arm64-cpu8
            cli_target: aarch64-unknown-linux-musl
            gnu_target: aarch64-unknown-linux-gnu
    uses: ./.github/workflows/build-deb.yml
    with:
      deb-version: ${{ inputs['deb-version'] }}
      checkout-ref: ${{ inputs['checkout-ref'] }}
      arch: ${{ matrix.arch }}
      runner: ${{ matrix.runner }}
      cli-target: ${{ matrix.cli_target }}
      gnu-target: ${{ matrix.gnu_target }}
