name: Docs

on:
    pull_request:
        branches: [main]
        types: [opened, synchronize]
        paths:
            - "docs/**"
    push:
        branches: [main]
    workflow_dispatch:

defaults:
    run:
        shell: bash

env:
    MISE_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    build:
        runs-on: build-arm64
        container:
            image: ghcr.io/nvidia/nemoclaw/ci:latest
            credentials:
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install tools
              run: mise install

            - name: Build documentation
              run: mise run docs:build:strict

            - name: Delete unnecessary files
              run: |
                  find _build -name .doctrees -prune -exec rm -rf {} \;
                  find _build -name .buildinfo -exec rm {} \;

            - name: Upload HTML
              uses: actions/upload-artifact@v4
              with:
                  name: html-build-artifact
                  path: _build/docs
                  if-no-files-found: error
                  retention-days: 1
            - name: Store PR information
              if: github.event_name == 'pull_request'
              run: |
                  mkdir ./pr
                  echo ${{ github.event.number }}              > ./pr/pr.txt
                  echo ${{ github.event.pull_request.merged }} > ./pr/merged.txt
                  echo ${{ github.event.action }}              > ./pr/action.txt

            - name: Upload PR information
              if: github.event_name == 'pull_request'
              uses: actions/upload-artifact@v4
              with:
                  name: pr
                  path: pr/
